#!/usr/bin/env node
// Package-manager manifests as PROJECTIONS of the pinned release
// manifest (plan v2.29 step 10, O71): the Homebrew formula and the
// winget manifests spell nothing but plugin/bin/manifest.env's version,
// base URL and pins — every url and sha256 in them is a pin the tag
// phase verified — so they are generated here, never hand-edited.
//
//   node scripts/packaging.js           rewrite packaging/**
//   node scripts/packaging.js --check   exit 1 naming any file that differs
//
// pin_release.js runs the generator after every pin, so the pin commit
// carries them; tests/it/packaging.rs runs --check and reads the pins
// back on its own. The formula covers the targets whose pins are set
// (a manifest before v1.7.0 pins three), the winget manifests the
// Windows installer; release.yml's homebrew-tap / winget-pr legs ship
// them behind the owner's secrets (docs/RELEASE.md §3).
//
// The formula carries no `version` line: Homebrew reads 1.x.y from the
// asset url (the `/v1.x.y/` path segment and the `ce-1.x.y-` stem both
// match its detector) and `brew audit` flags an explicit line as
// redundant. A manifest before v1.7.0 pins three targets, so its
// formula has no url on x86_64-macos / aarch64-linux; from v1.7.0 the
// tag phase refuses to publish with any pin empty, so a formula with a
// platform hole can only come from an older manifest. The winget files
// are kept pure ASCII (render() refuses otherwise): winget-pkgs wants
// UTF-8 with a BOM for anything beyond ASCII, and a BOM would have to
// survive --check and .gitattributes alike.
"use strict";
const fs = require("fs");
const path = require("path");
const { TARGETS, os, arch, asset, pinKey, parseManifest } = require("./roster");

const ROOT = path.join(__dirname, "..");
const FORMULA = "packaging/homebrew/Formula/codeeraser.rb";
const WINGET = "packaging/winget/manifests/s/skymanbp/CodeEraser";
const ID = "skymanbp.CodeEraser";
const SCHEMA = "1.10.0"; // the winget manifest schema version the files declare
const HOME = "https://codeeraser.dev";
const REPO = "https://github.com/skymanbp/CodeEraser";
const STAMP = "Generated by scripts/packaging.js from plugin/bin/manifest.env - do not edit.";

/** The crate's one-line description minus the leading product name (Homebrew's desc rule). */
function desc() {
  const toml = fs.readFileSync(path.join(ROOT, "cli", "Cargo.toml"), "utf8");
  const m = /^description = "(.*)"$/m.exec(toml);
  if (!m) throw new Error("cli/Cargo.toml has no description line");
  const d = m[1].replace(/^CodeEraser\s+—\s+/, "");
  return d[0].toUpperCase() + d.slice(1);
}

/** Non-Windows targets whose ce pin is set — Homebrew's platforms, as this manifest built them. */
function brewTargets(m) {
  return TARGETS.filter((k) => os(k) !== "windows" && m[pinKey("ce", k)]);
}

/** `on_macos` / `on_linux` blocks of `on_arm` / `on_intel` url + sha256 pairs for `what`. */
function systemBlocks(m, what, indent) {
  const pad = " ".repeat(indent);
  let out = "";
  for (const sys of ["macos", "linux"]) {
    const keys = brewTargets(m).filter((k) => os(k) === sys);
    if (!keys.length) continue;
    out += `${pad}on_${sys} do\n`;
    for (const k of keys) {
      out += `${pad}  on_${arch(k) === "aarch64" ? "arm" : "intel"} do\n`;
      out += `${pad}    url "${m.CE_BASE_URL}/${asset(what, m.CE_MANIFEST_VERSION, k)}"\n`;
      out += `${pad}    sha256 "${m[pinKey(what, k)]}"\n`;
      out += `${pad}  end\n`;
    }
    out += `${pad}end\n`;
  }
  return out.trimEnd();
}

function formula(m) {
  return [
    `# ${STAMP}`,
    `# CodeEraser ${m.CE_MANIFEST_VERSION}: every url is a release asset, every sha256 the pin release.yml verified before publishing.`,
    "class Codeeraser < Formula",
    `  desc "${desc()}"`,
    `  homepage "${HOME}"`,
    '  license "Apache-2.0"',
    "",
    systemBlocks(m, "ce", 2),
    "",
    '  resource "ce-core" do',
    systemBlocks(m, "ce-core", 4),
    "  end",
    "",
    "  def install",
    '    bin.install Dir["ce-#{version}-*"].fetch(0) => "ce"',
    '    resource("ce-core").stage { bin.install Dir["ce-core-#{version}-*"].fetch(0) => "ce-core" }',
    "  end",
    "",
    "  test do",
    '    assert_match version.to_s, shell_output("#{bin}/ce --version")',
    "  end",
    "end",
    "",
  ].join("\n");
}

/** The installer manifest's rows: the one x64 NSIS installer, at the pinned bytes. */
function installerRows(m, ver, key) {
  return [
    "InstallerType: nullsoft",
    "Scope: machine",
    "InstallModes:",
    "- interactive",
    "- silent",
    "- silentWithProgress",
    "InstallerSwitches:",
    "  Silent: /S",
    "  SilentWithProgress: /S",
    "UpgradeBehavior: install",
    "ElevationRequirement: elevatesSelf",
    // the ARP key the NSIS installer writes, measured on the desktop
    // install (HKLM\...\CurrentVersion\Uninstall\CodeEraser, 1.5.1, 2026-09-06)
    "ProductCode: CodeEraser",
    "Installers:",
    "- Architecture: x64",
    `  InstallerUrl: ${m.CE_BASE_URL}/${asset("CodeEraser", ver, key)}`,
    `  InstallerSha256: ${m[pinKey("CodeEraser", key)].toUpperCase()}`,
  ];
}

/** The default-locale manifest's rows: who publishes it and what it is. */
function localeRows(ver) {
  return [
    "PackageLocale: en-US",
    "Publisher: skymanbp",
    "PublisherUrl: https://github.com/skymanbp",
    `PublisherSupportUrl: ${REPO}/issues`,
    "PackageName: CodeEraser",
    `PackageUrl: ${HOME}`,
    "License: Apache-2.0",
    `LicenseUrl: ${REPO}/blob/main/LICENSE`,
    `ShortDescription: ${desc()}`,
    "Description: Measures, judges and gates LLM-induced code and document entropy - duplicated blocks, dead files, stale docs, structural sprawl - with a score that is only allowed to get better. The installer bundles the GUI, the ce command line and the ce-core judgment core.",
    "Moniker: codeeraser",
    "Tags:",
    "- cli",
    "- code-quality",
    "- dead-code",
    "- deduplication",
    "- haskell",
    "- rust",
    `ReleaseNotesUrl: ${REPO}/releases/tag/v${ver}`,
  ];
}

/** The three winget manifests, keyed by file name. */
function winget(m) {
  const ver = m.CE_MANIFEST_VERSION;
  const key = "x86_64-windows";
  const head = (kind) =>
    `# yaml-language-server: $schema=https://aka.ms/winget-manifest.${kind}.${SCHEMA}.schema.json\n# ${STAMP}\nPackageIdentifier: ${ID}\nPackageVersion: ${ver}\n`;
  const tail = (kind) => `ManifestType: ${kind}\nManifestVersion: ${SCHEMA}\n`;
  const lines = (rows) => rows.join("\n") + "\n";
  return {
    [`${ID}.yaml`]: head("version") + "DefaultLocale: en-US\n" + tail("version"),
    [`${ID}.installer.yaml`]: head("installer") + lines(installerRows(m, ver, key)) + tail("installer"),
    [`${ID}.locale.en-US.yaml`]: head("defaultLocale") + lines(localeRows(ver)) + tail("defaultLocale"),
  };
}

/** Every projected file: repo-relative path -> text. */
function render(m) {
  const files = { [FORMULA]: formula(m) };
  for (const [name, text] of Object.entries(winget(m))) {
    // winget-pkgs wants a BOM for anything beyond ASCII; pure ASCII sidesteps it
    if (!/^[\x00-\x7f]*$/.test(text)) throw new Error(`${name} carries non-ASCII bytes; the winget manifests are kept pure ASCII`);
    files[`${WINGET}/${m.CE_MANIFEST_VERSION}/${name}`] = text;
  }
  return files;
}

/** winget version directories other than the manifest's — a stale one would be submitted twice. */
function stale(ver) {
  const dir = path.join(ROOT, WINGET);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((d) => d !== ver)
    .map((d) => `${WINGET}/${d}`);
}

function main() {
  const check = process.argv.includes("--check");
  const m = parseManifest(fs.readFileSync(path.join(ROOT, "plugin", "bin", "manifest.env"), "utf8"));
  const drift = [];
  for (const [rel, text] of Object.entries(render(m))) {
    const abs = path.join(ROOT, rel);
    if (fs.existsSync(abs) && fs.readFileSync(abs, "utf8") === text) continue;
    drift.push(rel);
    if (check) continue;
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, text);
  }
  for (const rel of stale(m.CE_MANIFEST_VERSION)) {
    drift.push(`${rel} (stale)`);
    if (!check) fs.rmSync(path.join(ROOT, rel), { recursive: true, force: true });
  }
  if (!drift.length) {
    console.log("packaging: up to date");
    return;
  }
  if (check) {
    console.error(`packaging: out of date — ${drift.join(", ")}; run node scripts/packaging.js`);
    process.exit(1);
  }
  console.log(`packaging: rewrote ${drift.join(", ")}`);
}

main();
