# Generated by scripts/packaging.js from plugin/bin/manifest.env - do not edit.
# CodeEraser 1.6.0: every url is a release asset, every sha256 the pin release.yml verified before publishing.
class Codeeraser < Formula
  desc "Erase LLM-induced code & document entropy"
  homepage "https://codeeraser.dev"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.6.0/ce-1.6.0-aarch64-macos"
      sha256 "ee3bfde52dfd0c0bf8893d576128a469160da78a5041c70e1b80bb6248ddc422"
    end
  end
  on_linux do
    on_intel do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.6.0/ce-1.6.0-x86_64-linux"
      sha256 "10f3401a76263b4f6a8e9784089a1788207fec68d149aac1b40f34cfe239b76d"
    end
  end

  resource "ce-core" do
    on_macos do
      on_arm do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.6.0/ce-core-1.6.0-aarch64-macos"
        sha256 "beec61b4ac956176d0bf41cef932e7f50b4a0bcb9bc5237282fa7b7264b24ee4"
      end
    end
    on_linux do
      on_intel do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.6.0/ce-core-1.6.0-x86_64-linux"
        sha256 "4df14f0137c0ea162b92e118af7fb183f39bd64dd90e158a59a700656826b14d"
      end
    end
  end

  def install
    bin.install Dir["ce-#{version}-*"].fetch(0) => "ce"
    resource("ce-core").stage { bin.install Dir["ce-core-#{version}-*"].fetch(0) => "ce-core" }
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ce --version")
  end
end
