# Generated by scripts/packaging.js from plugin/bin/manifest.env - do not edit.
# CodeEraser 1.7.1: every url is a release asset, every sha256 the pin release.yml verified before publishing.
class Codeeraser < Formula
  desc "Erase LLM-induced code & document entropy"
  homepage "https://codeeraser.dev"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.1/ce-1.7.1-aarch64-macos"
      sha256 "6097ed290c98b318ea2d7f065a5bb4e8bb31e99d9f3dd6c56c08ce43cb16ffe6"
    end
    on_intel do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.1/ce-1.7.1-x86_64-macos"
      sha256 "a6f6f65cb87f6237725a936b3b481a66d9811373e4c1f5b0cf64d582dfd81f48"
    end
  end
  on_linux do
    on_intel do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.1/ce-1.7.1-x86_64-linux"
      sha256 "b4fde4f635480e5394be23565e666bd54cf8f801551fab91b1ba0ce4197bef70"
    end
    on_arm do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.1/ce-1.7.1-aarch64-linux"
      sha256 "a7fc74f66ddf382e9c61c66909b128ece5a34d95273f708749e6d6fc0994427b"
    end
  end

  resource "ce-core" do
    on_macos do
      on_arm do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.1/ce-core-1.7.1-aarch64-macos"
        sha256 "a10f501f44ffd6f9d091c75c8ac9fc29f61ea3c0a73585ff9420f0a9e01fb37e"
      end
      on_intel do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.1/ce-core-1.7.1-x86_64-macos"
        sha256 "7490a993503f0d733af58cb849fe1640c6643d834bc15d4fb7376bac1cee93d4"
      end
    end
    on_linux do
      on_intel do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.1/ce-core-1.7.1-x86_64-linux"
        sha256 "fc05d6327bc3514f2cf51a4a8a7fb14d42f3a736ab682157f2596d6c34503606"
      end
      on_arm do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.1/ce-core-1.7.1-aarch64-linux"
        sha256 "f6d2ca1c0ff8cdc866a9daa2d53ca8339c8ff3f279543276845ab37fdd94029c"
      end
    end
  end

  def install
    bin.install Dir["ce-#{version}-*"].fetch(0) => "ce"
    resource("ce-core").stage { bin.install Dir["ce-core-#{version}-*"].fetch(0) => "ce-core" }
    # a raw release binary lands 0644 (curl) and the cleaner keeps only the x bit it finds
    chmod 0755, [bin/"ce", bin/"ce-core"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ce --version")
  end
end
